project:
  type: hugo
  output-dir: _hugo
  post-render: /bin/sh -c "cd _hugo && hugo --cleanDestinationDir --minify && /bin/cp -rf public ../_public"
format:
  hugo-md:
    code-fold: true
execute:
  echo: false
  warning: false
  message: false
  cache: false
  freeze: auto
engine: knitr
knitr:
  opts_chunk:
    out.width: "100%"
    dev: svglite
    dev.args: { scaling: 1, bg: "transparent" }
editor: source
editor_options:
  chunk_output_type: console
# commands:
#   clean: "rm -rf _book"
#   preview: "quarto preview --port 7777"
#   publish: "quarto render --to html && rsync -av _book/ myserver:/var/www/"