project:
  type: hugo
  output-dir: _hugo
  pre-render: /bin/sh -c "R -e 'renv::init()'"
  post-render: |
    /bin/sh -c "cd _hugo && \
    hugo --cleanDestinationDir && \
    /bin/cp -rf public ../_public"
  # post-render: /bin/sh -c "cd hugo &&  hugo --cleanDestinationDir"
format:
  hugo-md:
    code-fold: true
execute:
  echo: false
  warning: false
  message: false
  cache: false
  freeze: auto
engine: knitr
knitr:
  opts_chunk:
    out.width: "100%"
    # dev: ragg_png
    dev: svglite
    dev.args: { scaling: 1, bg: "transparent" }
editor: source
editor_options:
  chunk_output_type: console
